// Auto-lifted from the legacy static site (see legacy/index.html).
// Hero, Services, Projects, and the CTA/contact section are now React components. Only the
// nav/tech-bar (top) and the footer (bottom) remain as injected legacy markup, split around
// the React sections. The <main id="content"> wrapper lives in app/(tracerlabs)/page.tsx.
// The legacy "dealflow" contact modal was removed with the contact section (replaced by the
// in-browser voice-agent CTA). Retired section-by-section as we componentize.

// nav + technology logo bar (renders above <Services/>)
export const MARKUP_TOP = "        <!-- Navigation -->\n        <nav id=\"main-nav\">\n            <div class=\"nav-container\">\n                <a href=\"#\" class=\"logo\">\n                    <img src=\"./assets/logo-dark.png\" alt=\"tracerlabs\" class=\"logo-img\">\n                </a>\n                <div class=\"nav-links\">\n                    <a class=\"non-cta\" href=\"#services\">Services</a>\n                    <a class=\"non-cta\" href=\"#works\">Works</a>\n                    <a href=\"#contact\" id=\"cta\">Contact Us</a>\n                </div>\n                <div class=\"theme-toggle-wrapper\">\n                    <label class=\"theme-toggle\" for=\"theme-toggle-checkbox\">\n                        <input type=\"checkbox\" id=\"theme-toggle-checkbox\" checked>\n                        <div class=\"slider\">\n                            <div class=\"icons\">\n                                <span class=\"sun\">☀️</span>\n                                <span class=\"moon\">🌙</span>\n                            </div>\n                        </div>\n                    </label>\n                </div>\n            </div>\n        </nav>\n        <div class=\"nav-placeholder\"></div>\n\n        <!-- Technology Logo Bar -->\n        <div class=\"tech-scroll\">\n            <div class=\"tech-container\">\n                <div class=\"tech-track\">\n                    <!-- First set of logos -->\n                    <div class=\"tech-logo\">\n                        <img src=\"/assets/aws.png\" alt=\"AWS\" />\n                    </div>\n                    <div class=\"tech-logo\">\n                        <img src=\"/assets/google.jpg\" alt=\"Google Cloud\" />\n                    </div>\n                    <div class=\"tech-logo\">\n                        <img src=\"/assets/firebase.png\" alt=\"Firebase\" />\n                    </div>\n                    <div class=\"tech-logo\">\n                        <img src=\"/assets/flutter.png\" alt=\"Flutter\" />\n                    </div>\n                    <div class=\"tech-logo\">\n                        <img src=\"/assets/next.jpeg\" alt=\" Next JS\" />\n                    </div>\n                    <!-- Duplicate set for seamless scrolling -->\n                    <div class=\"tech-logo\">\n                        <img src=\"/assets/ethereum.png\" alt=\"ethereum\" />\n                    </div>\n                    <div class=\"tech-logo\">\n                        <img src=\"/assets/anthropic.png\" alt=\"anthropic\" />\n                    </div>\n                    <div class=\"tech-logo\">\n                        <img src=\"/assets/gemini.png\" alt=\"google gemini\" />\n                    </div>\n                    <div class=\"tech-logo\">\n                        <img src=\"/assets/crew-ai.png\" alt=\"crew ai\" />\n                    </div>\n                </div>\n            </div>\n        </div>\n    \n        ";

// footer only (renders below the <Cta/> section)
export const MARKUP_BOTTOM = "<!-- Footer -->\n        <footer id=\"main-footer\">\n            <div class=\"container\">\n                <p>This webpage was built by <a href=\"https://github.com/subaiyalShk\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"github-link\">subaiyalShk</a> using pure HTML, CSS and JS. Checkout my profile for more projects.</p>\n            </div>\n        </footer>\n    ";
